- hosts: tag_work_web
  tasks:
      - name : Installing Apache webserver
        package:
           name: httpd
           state: present
      - name: Copy Files to Webserver Document Root
        copy:
            src: '<path_to_file>/index.html'
            dest: '/var/www/html/index.html'
      - name: Starting Httpd Service
        service:
            name: httpd
            state: started
- hosts: tag_work_load
  tasks:
      - name: Installing Haproxy Server
        package:
            name: haproxy
            state: present
      - name: Templating 
        template:
            src: '<path_to_file>/haproxy.cfg.j2'
            dest: '/etc/haproxy/haproxy.cfg'
        register: x
        ignore_errors: true
      - name: Starting Service
        service: 
            name: haproxy
            state: started 
        when: x.changed == true
        ignore_errors: true
      - debug:
            var: x
